### ISSUE TITLE
Bug: Bitbucket RSA host key rotation

### ISSUE THREAD

**Issue by lorencr7** [guitarrapc/git-shallow-clone-orb#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Orb version

2.5.0

### Current behavior

Checkout of bitbucket repo fails. Bitbucket is rotating the host keys (https://bitbucket.org/blog/ssh-host-key-changes)
The keys in the orb need to be updated with the new ones provided from bitbucket

### Minimum reproduction config

any bitbucket checkout

**Comment by pacokleitz** [comment]
Hello, thank you for the quick fix. Are you going to publish the updated orb ?

**Comment by guitarrapc** [comment]
Hi, I've published orb v2.6.0. Please try it and let me know if there are still an issue with.
https://circleci.com/developer/orbs/orb/guitarrapc/git-shallow-clone?version=2.6.0
