### ISSUE TITLE
[Feature Request] Add an option "path" same as the built in step "checkout"

### ISSUE THREAD

**Issue by suzuki-shunsuke** [guitarrapc/git-shallow-clone-orb#5]
* [checkout](https://circleci.com/docs/2.0/configuration-reference/#checkout)

Thank you for your great project.
This orb is very useful!

I have a feature request to add an option "path" same as the built in step "checkout".
It is useful we can change the destination where the repository is cloned.

Thank you.

**Comment by guitarrapc** [comment]
merged! thank you.

**Comment by guitarrapc** [comment]
released 1.1.0
https://circleci.com/orbs/registry/orb/guitarrapc/git-shallow-clone?version=1.1.0

**Comment by suzuki-shunsuke** [comment]
Thank you for releasing quickly!
It woks fine 🎉
